version: 1
config:
  name: "example-repo"
  repush_on_actor: cep21
  ExtraContent: "Some custom configuration!"
  extra_content: "Some custom configuration!"

children:
  - source: github.com/getsyncer/public-sync-modules/opensourcegolib

logic:
  - source: github.com/getsyncer/example-sync/helloworld

syncs:
  - logic: helloworld
    config:
      ExtraContent: "Some custom configuration!"
