version: 1
config:
  name: "example-repo"

children:
  - source: github.com/getsyncer/public-sync-modules/opensourcegolib

logic:
  - source: github.com/getsyncer/example-sync/helloworld

syncs:
  - logic: helloworld
    config:
      message: "Some custom configuration!"
